/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageItemDto } from '../../models/page-item-dto';

export interface SearchRejetMessages$Params {
  productName?: string;
  page?: number;
  size?: number;
  sortField?: string;
  sortDirection?: 'DESC' | 'ASC';
}

export function searchRejetMessages(http: HttpClient, rootUrl: string, params?: SearchRejetMessages$Params, context?: HttpContext): Observable<StrictHttpResponse<PageItemDto>> {
  const rb = new RequestBuilder(rootUrl, searchRejetMessages.PATH, 'get');
  if (params) {
    rb.query('productName', params.productName, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sortField', params.sortField, {});
    rb.query('sortDirection', params.sortDirection, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageItemDto>;
    })
  );
}

searchRejetMessages.PATH = '/v1/api/items/listProjet';
