/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { authenticate } from '../fn/auth/authenticate';
import { Authenticate$Params } from '../fn/auth/authenticate';
import { AuthenticationResponce } from '../models/authentication-responce';
import { regester } from '../fn/auth/regester';
import { Regester$Params } from '../fn/auth/regester';

@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `regester()` */
  static readonly RegesterPath = '/api/v1/auth/register';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `regester()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  regester$Response(params: Regester$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenticationResponce>> {
    return regester(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `regester$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  regester(params: Regester$Params, context?: HttpContext): Observable<AuthenticationResponce> {
    return this.regester$Response(params, context).pipe(
      map((r: StrictHttpResponse<AuthenticationResponce>): AuthenticationResponce => r.body)
    );
  }

  /** Path part for operation `authenticate()` */
  static readonly AuthenticatePath = '/api/v1/auth/authenticated';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authenticate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authenticate$Response(params: Authenticate$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenticationResponce>> {
    return authenticate(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authenticate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authenticate(params: Authenticate$Params, context?: HttpContext): Observable<AuthenticationResponce> {
    return this.authenticate$Response(params, context).pipe(
      map((r: StrictHttpResponse<AuthenticationResponce>): AuthenticationResponce => r.body)
    );
  }

}
