/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addItem } from '../fn/item-controller/add-item';
import { AddItem$Params } from '../fn/item-controller/add-item';
import { deleteItem } from '../fn/item-controller/delete-item';
import { DeleteItem$Params } from '../fn/item-controller/delete-item';
import { getItem } from '../fn/item-controller/get-item';
import { GetItem$Params } from '../fn/item-controller/get-item';
import { ItemDto } from '../models/item-dto';
import { PageItemDto } from '../models/page-item-dto';
import { searchRejetMessages } from '../fn/item-controller/search-rejet-messages';
import { SearchRejetMessages$Params } from '../fn/item-controller/search-rejet-messages';
import { updateItem } from '../fn/item-controller/update-item';
import { UpdateItem$Params } from '../fn/item-controller/update-item';

@Injectable({ providedIn: 'root' })
export class ItemControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateItem()` */
  static readonly UpdateItemPath = '/v1/api/items/update/{itemId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateItem()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateItem$Response(params: UpdateItem$Params, context?: HttpContext): Observable<StrictHttpResponse<ItemDto>> {
    return updateItem(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateItem$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateItem(params: UpdateItem$Params, context?: HttpContext): Observable<ItemDto> {
    return this.updateItem$Response(params, context).pipe(
      map((r: StrictHttpResponse<ItemDto>): ItemDto => r.body)
    );
  }

  /** Path part for operation `addItem()` */
  static readonly AddItemPath = '/v1/api/items/add';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addItem()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addItem$Response(params: AddItem$Params, context?: HttpContext): Observable<StrictHttpResponse<ItemDto>> {
    return addItem(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addItem$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addItem(params: AddItem$Params, context?: HttpContext): Observable<ItemDto> {
    return this.addItem$Response(params, context).pipe(
      map((r: StrictHttpResponse<ItemDto>): ItemDto => r.body)
    );
  }

  /** Path part for operation `getItem()` */
  static readonly GetItemPath = '/v1/api/items/{itemId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getItem()` instead.
   *
   * This method doesn't expect any request body.
   */
  getItem$Response(params: GetItem$Params, context?: HttpContext): Observable<StrictHttpResponse<ItemDto>> {
    return getItem(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getItem$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getItem(params: GetItem$Params, context?: HttpContext): Observable<ItemDto> {
    return this.getItem$Response(params, context).pipe(
      map((r: StrictHttpResponse<ItemDto>): ItemDto => r.body)
    );
  }

  /** Path part for operation `searchRejetMessages()` */
  static readonly SearchRejetMessagesPath = '/v1/api/items/listProjet';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchRejetMessages()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchRejetMessages$Response(params?: SearchRejetMessages$Params, context?: HttpContext): Observable<StrictHttpResponse<PageItemDto>> {
    return searchRejetMessages(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchRejetMessages$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchRejetMessages(params?: SearchRejetMessages$Params, context?: HttpContext): Observable<PageItemDto> {
    return this.searchRejetMessages$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageItemDto>): PageItemDto => r.body)
    );
  }

  /** Path part for operation `deleteItem()` */
  static readonly DeleteItemPath = '/v1/api/items/delete/{itemId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteItem()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteItem$Response(params: DeleteItem$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteItem(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteItem$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteItem(params: DeleteItem$Params, context?: HttpContext): Observable<void> {
    return this.deleteItem$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
