/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CostumerDto } from '../../models/costumer-dto';

export interface FindAllTest$Params {
}

export function findAllTest(http: HttpClient, rootUrl: string, params?: FindAllTest$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CostumerDto>>> {
  const rb = new RequestBuilder(rootUrl, findAllTest.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CostumerDto>>;
    })
  );
}

findAllTest.PATH = '/api/v1/test/findAll';
