/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartDto } from '../../models/cart-dto';
import { ItemDto } from '../../models/item-dto';

export interface AddProductsToCart$Params {
  clientId: number;
      body: Array<ItemDto>
}

export function addProductsToCart(http: HttpClient, rootUrl: string, params: AddProductsToCart$Params, context?: HttpContext): Observable<StrictHttpResponse<CartDto>> {
  const rb = new RequestBuilder(rootUrl, addProductsToCart.PATH, 'post');
  if (params) {
    rb.path('clientId', params.clientId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartDto>;
    })
  );
}

addProductsToCart.PATH = '/api/v1/cart/{clientId}/add';
