/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Cart } from '../../models/cart';

export interface GetOrCreateActiveCart$Params {
  costumerId: number;
}

export function getOrCreateActiveCart(http: HttpClient, rootUrl: string, params: GetOrCreateActiveCart$Params, context?: HttpContext): Observable<StrictHttpResponse<Cart>> {
  const rb = new RequestBuilder(rootUrl, getOrCreateActiveCart.PATH, 'get');
  if (params) {
    rb.path('costumerId', params.costumerId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Cart>;
    })
  );
}

getOrCreateActiveCart.PATH = '/api/v1/cart/getOrCreateActiveCart/{costumerId}';
