/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemDto } from '../models/item-dto';
export interface CartDto {
  clientId?: number;
  items?: Array<ItemDto>;
  oid?: number;
  status?: string;
}
