/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CostumerDto {
  age?: number;
  email?: string;
  name?: string;
  oid?: number;
  password?: string;
  role?: string;
}
