/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Cart } from '../models/cart';
import { GrantedAuthority } from '../models/granted-authority';
export interface Costumer {
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  carts?: Array<Cart>;
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  name?: string;
  oid?: number;
  password?: string;
  role?: 'ADMIN' | 'USER';
  username?: string;
}
