/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthenticationResponce } from '../../models/authentication-responce';
import { RegisterRequest } from '../../models/register-request';

export interface Regester$Params {
      body: RegisterRequest
}

export function regester(http: HttpClient, rootUrl: string, params: Regester$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenticationResponce>> {
  const rb = new RequestBuilder(rootUrl, regester.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthenticationResponce>;
    })
  );
}

regester.PATH = '/api/v1/auth/register';
